services:
  frontend:
    hostname: frontend
    build: ./frontend/deepseek-rag
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  app:
    build: ./backend
    hostname: app
    ports:
      - "5000:5000"
