services:
  frontend:
    hostname: frontend
    build: 
      context: ./frontend/deepseek-rag
      # no_cache: true
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  app:
    build: ./backend
    hostname: app
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_vol:/.ollama/models
    environment:
      - OLLAMA_MODELS=/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_vol:
    external: true
